-- SQL di seeding per popolare zones_to_scrape con le 100 zone italiane principali
-- Questo file inserisce 1500 righe (100 zone × 3 fonti × 5 categorie)
-- È idempotente: puoi eseguirlo più volte senza creare duplicati

-- Prima cancelliamo eventuali zone esistenti (opzionale)
-- TRUNCATE TABLE zones_to_scrape;

-- Inserimento massivo delle zone per tutte le combinazioni
INSERT INTO zones_to_scrape (source, category, location_name, score) 
VALUES
-- GOOGLE MAPS - RISTORANTI
('google_maps', 'ristoranti', 'Milano Centro', 100),
('google_maps', 'ristoranti', 'Milano Navigli', 95),
('google_maps', 'ristoranti', 'Roma Centro Storico', 100),
('google_maps', 'ristoranti', 'Roma Eur', 90),
('google_maps', 'ristoranti', 'Roma Trastevere', 95),
('google_maps', 'ristoranti', 'Napoli Centro', 100),
('google_maps', 'ristoranti', 'Napoli Vomero', 85),
('google_maps', 'ristoranti', 'Torino Centro', 90),
('google_maps', 'ristoranti', 'Bologna Centro', 90),
('google_maps', 'ristoranti', 'Firenze Centro', 95),
('google_maps', 'ristoranti', 'Palermo Centro', 85),
('google_maps', 'ristoranti', 'Genova Centro', 80),
('google_maps', 'ristoranti', 'Bari Centro', 75),
('google_maps', 'ristoranti', 'Catania Centro', 75),
('google_maps', 'ristoranti', 'Verona Centro', 85),
('google_maps', 'ristoranti', 'Venezia Mestre', 80),
('google_maps', 'ristoranti', 'Padova Centro', 80),
('google_maps', 'ristoranti', 'Trieste Centro', 75),
('google_maps', 'ristoranti', 'Brescia Centro', 75),
('google_maps', 'ristoranti', 'Bergamo Bassa', 70),
('google_maps', 'ristoranti', 'Lecce Centro', 70),
('google_maps', 'ristoranti', 'Taranto Centro', 65),
('google_maps', 'ristoranti', 'Reggio Calabria', 65),
('google_maps', 'ristoranti', 'Perugia Centro', 70),
('google_maps', 'ristoranti', 'Cagliari Centro', 75),
('google_maps', 'ristoranti', 'Trento Centro', 70),
('google_maps', 'ristoranti', 'Bolzano Centro', 70),
('google_maps', 'ristoranti', 'Salerno Centro', 70),
('google_maps', 'ristoranti', 'Rimini Centro', 75),
('google_maps', 'ristoranti', 'Parma Centro', 75),
('google_maps', 'ristoranti', 'Modena Centro', 70),
('google_maps', 'ristoranti', 'Pescara Centro', 70),
('google_maps', 'ristoranti', 'Livorno Centro', 65),
('google_maps', 'ristoranti', 'Sassari Centro', 65),
('google_maps', 'ristoranti', 'Ferrara Centro', 65),
('google_maps', 'ristoranti', 'Latina Centro', 65),
('google_maps', 'ristoranti', 'Arezzo Centro', 60),
('google_maps', 'ristoranti', 'Pisa Centro', 70),
('google_maps', 'ristoranti', 'Lucca Centro', 65),
('google_maps', 'ristoranti', 'Foggia Centro', 60),
('google_maps', 'ristoranti', 'L''Aquila Centro', 60),
('google_maps', 'ristoranti', 'Grosseto Centro', 55),
('google_maps', 'ristoranti', 'Treviso Centro', 65),
('google_maps', 'ristoranti', 'Varese Centro', 65),
('google_maps', 'ristoranti', 'Novara Centro', 60),
('google_maps', 'ristoranti', 'Monza Centro', 70),
('google_maps', 'ristoranti', 'Como Centro', 65),
('google_maps', 'ristoranti', 'Vercelli', 55),
('google_maps', 'ristoranti', 'Asti', 55),
('google_maps', 'ristoranti', 'Alessandria', 55),
('google_maps', 'ristoranti', 'Viterbo', 55),
('google_maps', 'ristoranti', 'Terni', 55),
('google_maps', 'ristoranti', 'Ragusa', 55),
('google_maps', 'ristoranti', 'Siracusa', 60),
('google_maps', 'ristoranti', 'Agrigento', 55),
('google_maps', 'ristoranti', 'Trapani', 55),
('google_maps', 'ristoranti', 'Cosenza', 55),
('google_maps', 'ristoranti', 'Crotone', 50),
('google_maps', 'ristoranti', 'Catanzaro', 55),
('google_maps', 'ristoranti', 'Matera', 60),
('google_maps', 'ristoranti', 'Potenza', 55),
('google_maps', 'ristoranti', 'Campobasso', 50),
('google_maps', 'ristoranti', 'Benevento', 50),
('google_maps', 'ristoranti', 'Avellino', 50),
('google_maps', 'ristoranti', 'Caserta', 55),
('google_maps', 'ristoranti', 'Brindisi', 55),
('google_maps', 'ristoranti', 'Andria', 50),
('google_maps', 'ristoranti', 'Barletta', 50),
('google_maps', 'ristoranti', 'Trani', 50),
('google_maps', 'ristoranti', 'Molfetta', 50),
('google_maps', 'ristoranti', 'Altamura', 50),
('google_maps', 'ristoranti', 'Torre del Greco', 55),
('google_maps', 'ristoranti', 'Giugliano in Campania', 55),
('google_maps', 'ristoranti', 'Scafati', 50),
('google_maps', 'ristoranti', 'Castellammare di Stabia', 55),
('google_maps', 'ristoranti', 'Afragola', 50),
('google_maps', 'ristoranti', 'Aversa', 50),
('google_maps', 'ristoranti', 'Nocera Inferiore', 50),
('google_maps', 'ristoranti', 'Cava de'' Tirreni', 50),
('google_maps', 'ristoranti', 'Eboli', 50),
('google_maps', 'ristoranti', 'Battipaglia', 50),
('google_maps', 'ristoranti', 'Tivoli', 55),
('google_maps', 'ristoranti', 'Guidonia Montecelio', 50),
('google_maps', 'ristoranti', 'Pomezia', 55),
('google_maps', 'ristoranti', 'Aprilia', 50),
('google_maps', 'ristoranti', 'Frosinone', 55),
('google_maps', 'ristoranti', 'Velletri', 50),
('google_maps', 'ristoranti', 'Anzio', 55),
('google_maps', 'ristoranti', 'Nettuno', 50),
('google_maps', 'ristoranti', 'Ladispoli', 50),
('google_maps', 'ristoranti', 'Civitavecchia', 55),
('google_maps', 'ristoranti', 'Alghero', 60),
('google_maps', 'ristoranti', 'Olbia', 65),
('google_maps', 'ristoranti', 'Nuoro', 50),
('google_maps', 'ristoranti', 'Iglesias', 50),
('google_maps', 'ristoranti', 'Oristano', 50),
('google_maps', 'ristoranti', 'Sanremo', 65),
('google_maps', 'ristoranti', 'Imperia', 55),
('google_maps', 'ristoranti', 'Ventimiglia', 50),
('google_maps', 'ristoranti', 'Sesto San Giovanni', 70),

-- GOOGLE MAPS - BARBERIE
('google_maps', 'barberie', 'Milano Centro', 90),
('google_maps', 'barberie', 'Milano Navigli', 85),
('google_maps', 'barberie', 'Roma Centro Storico', 90),
('google_maps', 'barberie', 'Roma Eur', 80),
('google_maps', 'barberie', 'Roma Trastevere', 85),
('google_maps', 'barberie', 'Napoli Centro', 90),
('google_maps', 'barberie', 'Napoli Vomero', 75),
('google_maps', 'barberie', 'Torino Centro', 80),
('google_maps', 'barberie', 'Bologna Centro', 80),
('google_maps', 'barberie', 'Firenze Centro', 85),
('google_maps', 'barberie', 'Palermo Centro', 75),
('google_maps', 'barberie', 'Genova Centro', 70),
('google_maps', 'barberie', 'Bari Centro', 65),
('google_maps', 'barberie', 'Catania Centro', 65),
('google_maps', 'barberie', 'Verona Centro', 75),
('google_maps', 'barberie', 'Venezia Mestre', 70),
('google_maps', 'barberie', 'Padova Centro', 70),
('google_maps', 'barberie', 'Trieste Centro', 65),
('google_maps', 'barberie', 'Brescia Centro', 65),
('google_maps', 'barberie', 'Bergamo Bassa', 60),
('google_maps', 'barberie', 'Lecce Centro', 60),
('google_maps', 'barberie', 'Taranto Centro', 55),
('google_maps', 'barberie', 'Reggio Calabria', 55),
('google_maps', 'barberie', 'Perugia Centro', 60),
('google_maps', 'barberie', 'Cagliari Centro', 65),
('google_maps', 'barberie', 'Trento Centro', 60),
('google_maps', 'barberie', 'Bolzano Centro', 60),
('google_maps', 'barberie', 'Salerno Centro', 60),
('google_maps', 'barberie', 'Rimini Centro', 65),
('google_maps', 'barberie', 'Parma Centro', 65),
('google_maps', 'barberie', 'Modena Centro', 60),
('google_maps', 'barberie', 'Pescara Centro', 60),
('google_maps', 'barberie', 'Livorno Centro', 55),
('google_maps', 'barberie', 'Sassari Centro', 55),
('google_maps', 'barberie', 'Ferrara Centro', 55),
('google_maps', 'barberie', 'Latina Centro', 55),
('google_maps', 'barberie', 'Arezzo Centro', 50),
('google_maps', 'barberie', 'Pisa Centro', 60),
('google_maps', 'barberie', 'Lucca Centro', 55),
('google_maps', 'barberie', 'Foggia Centro', 50),
('google_maps', 'barberie', 'L''Aquila Centro', 50),
('google_maps', 'barberie', 'Grosseto Centro', 45),
('google_maps', 'barberie', 'Treviso Centro', 55),
('google_maps', 'barberie', 'Varese Centro', 55),
('google_maps', 'barberie', 'Novara Centro', 50),
('google_maps', 'barberie', 'Monza Centro', 60),
('google_maps', 'barberie', 'Como Centro', 55),
('google_maps', 'barberie', 'Vercelli', 45),
('google_maps', 'barberie', 'Asti', 45),
('google_maps', 'barberie', 'Alessandria', 45),
('google_maps', 'barberie', 'Viterbo', 45),
('google_maps', 'barberie', 'Terni', 45),
('google_maps', 'barberie', 'Ragusa', 45),
('google_maps', 'barberie', 'Siracusa', 50),
('google_maps', 'barberie', 'Agrigento', 45),
('google_maps', 'barberie', 'Trapani', 45),
('google_maps', 'barberie', 'Cosenza', 45),
('google_maps', 'barberie', 'Crotone', 40),
('google_maps', 'barberie', 'Catanzaro', 45),
('google_maps', 'barberie', 'Matera', 50),
('google_maps', 'barberie', 'Potenza', 45),
('google_maps', 'barberie', 'Campobasso', 40),
('google_maps', 'barberie', 'Benevento', 40),
('google_maps', 'barberie', 'Avellino', 40),
('google_maps', 'barberie', 'Caserta', 45),
('google_maps', 'barberie', 'Brindisi', 45),
('google_maps', 'barberie', 'Andria', 40),
('google_maps', 'barberie', 'Barletta', 40),
('google_maps', 'barberie', 'Trani', 40),
('google_maps', 'barberie', 'Molfetta', 40),
('google_maps', 'barberie', 'Altamura', 40),
('google_maps', 'barberie', 'Torre del Greco', 45),
('google_maps', 'barberie', 'Giugliano in Campania', 45),
('google_maps', 'barberie', 'Scafati', 40),
('google_maps', 'barberie', 'Castellammare di Stabia', 45),
('google_maps', 'barberie', 'Afragola', 40),
('google_maps', 'barberie', 'Aversa', 40),
('google_maps', 'barberie', 'Nocera Inferiore', 40),
('google_maps', 'barberie', 'Cava de'' Tirreni', 40),
('google_maps', 'barberie', 'Eboli', 40),
('google_maps', 'barberie', 'Battipaglia', 40),
('google_maps', 'barberie', 'Tivoli', 45),
('google_maps', 'barberie', 'Guidonia Montecelio', 40),
('google_maps', 'barberie', 'Pomezia', 45),
('google_maps', 'barberie', 'Aprilia', 40),
('google_maps', 'barberie', 'Frosinone', 45),
('google_maps', 'barberie', 'Velletri', 40),
('google_maps', 'barberie', 'Anzio', 45),
('google_maps', 'barberie', 'Nettuno', 40),
('google_maps', 'barberie', 'Ladispoli', 40),
('google_maps', 'barberie', 'Civitavecchia', 45),
('google_maps', 'barberie', 'Alghero', 50),
('google_maps', 'barberie', 'Olbia', 55),
('google_maps', 'barberie', 'Nuoro', 40),
('google_maps', 'barberie', 'Iglesias', 40),
('google_maps', 'barberie', 'Oristano', 40),
('google_maps', 'barberie', 'Sanremo', 55),
('google_maps', 'barberie', 'Imperia', 45),
('google_maps', 'barberie', 'Ventimiglia', 40),
('google_maps', 'barberie', 'Sesto San Giovanni', 60),

-- GOOGLE MAPS - WEB AGENCY
('google_maps', 'web agency', 'Milano Centro', 95),
('google_maps', 'web agency', 'Milano Navigli', 90),
('google_maps', 'web agency', 'Roma Centro Storico', 95),
('google_maps', 'web agency', 'Roma Eur', 85),
('google_maps', 'web agency', 'Roma Trastevere', 80),
('google_maps', 'web agency', 'Napoli Centro', 85),
('google_maps', 'web agency', 'Napoli Vomero', 70),
('google_maps', 'web agency', 'Torino Centro', 85),
('google_maps', 'web agency', 'Bologna Centro', 85),
('google_maps', 'web agency', 'Firenze Centro', 80),
('google_maps', 'web agency', 'Palermo Centro', 70),
('google_maps', 'web agency', 'Genova Centro', 75),
('google_maps', 'web agency', 'Bari Centro', 70),
('google_maps', 'web agency', 'Catania Centro', 70),
('google_maps', 'web agency', 'Verona Centro', 75),
('google_maps', 'web agency', 'Venezia Mestre', 70),
('google_maps', 'web agency', 'Padova Centro', 75),
('google_maps', 'web agency', 'Trieste Centro', 65),
('google_maps', 'web agency', 'Brescia Centro', 70),
('google_maps', 'web agency', 'Bergamo Bassa', 70),
('google_maps', 'web agency', 'Lecce Centro', 60),
('google_maps', 'web agency', 'Taranto Centro', 55),
('google_maps', 'web agency', 'Reggio Calabria', 55),
('google_maps', 'web agency', 'Perugia Centro', 65),
('google_maps', 'web agency', 'Cagliari Centro', 65),
('google_maps', 'web agency', 'Trento Centro', 65),
('google_maps', 'web agency', 'Bolzano Centro', 65),
('google_maps', 'web agency', 'Salerno Centro', 60),
('google_maps', 'web agency', 'Rimini Centro', 60),
('google_maps', 'web agency', 'Parma Centro', 65),
('google_maps', 'web agency', 'Modena Centro', 65),
('google_maps', 'web agency', 'Pescara Centro', 60),
('google_maps', 'web agency', 'Livorno Centro', 55),
('google_maps', 'web agency', 'Sassari Centro', 55),
('google_maps', 'web agency', 'Ferrara Centro', 55),
('google_maps', 'web agency', 'Latina Centro', 55),
('google_maps', 'web agency', 'Arezzo Centro', 55),
('google_maps', 'web agency', 'Pisa Centro', 60),
('google_maps', 'web agency', 'Lucca Centro', 55),
('google_maps', 'web agency', 'Foggia Centro', 50),
('google_maps', 'web agency', 'L''Aquila Centro', 50),
('google_maps', 'web agency', 'Grosseto Centro', 50),
('google_maps', 'web agency', 'Treviso Centro', 60),
('google_maps', 'web agency', 'Varese Centro', 60),
('google_maps', 'web agency', 'Novara Centro', 55),
('google_maps', 'web agency', 'Monza Centro', 70),
('google_maps', 'web agency', 'Como Centro', 60),
('google_maps', 'web agency', 'Vercelli', 50),
('google_maps', 'web agency', 'Asti', 50),
('google_maps', 'web agency', 'Alessandria', 50),
('google_maps', 'web agency', 'Viterbo', 50),
('google_maps', 'web agency', 'Terni', 50),
('google_maps', 'web agency', 'Ragusa', 45),
('google_maps', 'web agency', 'Siracusa', 50),
('google_maps', 'web agency', 'Agrigento', 45),
('google_maps', 'web agency', 'Trapani', 45),
('google_maps', 'web agency', 'Cosenza', 50),
('google_maps', 'web agency', 'Crotone', 45),
('google_maps', 'web agency', 'Catanzaro', 50),
('google_maps', 'web agency', 'Matera', 50),
('google_maps', 'web agency', 'Potenza', 50),
('google_maps', 'web agency', 'Campobasso', 45),
('google_maps', 'web agency', 'Benevento', 45),
('google_maps', 'web agency', 'Avellino', 45),
('google_maps', 'web agency', 'Caserta', 50),
('google_maps', 'web agency', 'Brindisi', 50),
('google_maps', 'web agency', 'Andria', 45),
('google_maps', 'web agency', 'Barletta', 45),
('google_maps', 'web agency', 'Trani', 45),
('google_maps', 'web agency', 'Molfetta', 45),
('google_maps', 'web agency', 'Altamura', 45),
('google_maps', 'web agency', 'Torre del Greco', 50),
('google_maps', 'web agency', 'Giugliano in Campania', 50),
('google_maps', 'web agency', 'Scafati', 45),
('google_maps', 'web agency', 'Castellammare di Stabia', 50),
('google_maps', 'web agency', 'Afragola', 45),
('google_maps', 'web agency', 'Aversa', 45),
('google_maps', 'web agency', 'Nocera Inferiore', 45),
('google_maps', 'web agency', 'Cava de'' Tirreni', 45),
('google_maps', 'web agency', 'Eboli', 45),
('google_maps', 'web agency', 'Battipaglia', 45),
('google_maps', 'web agency', 'Tivoli', 50),
('google_maps', 'web agency', 'Guidonia Montecelio', 45),
('google_maps', 'web agency', 'Pomezia', 50),
('google_maps', 'web agency', 'Aprilia', 45),
('google_maps', 'web agency', 'Frosinone', 50),
('google_maps', 'web agency', 'Velletri', 45),
('google_maps', 'web agency', 'Anzio', 50),
('google_maps', 'web agency', 'Nettuno', 45),
('google_maps', 'web agency', 'Ladispoli', 45),
('google_maps', 'web agency', 'Civitavecchia', 50),
('google_maps', 'web agency', 'Alghero', 55),
('google_maps', 'web agency', 'Olbia', 60),
('google_maps', 'web agency', 'Nuoro', 45),
('google_maps', 'web agency', 'Iglesias', 45),
('google_maps', 'web agency', 'Oristano', 45),
('google_maps', 'web agency', 'Sanremo', 60),
('google_maps', 'web agency', 'Imperia', 50),
('google_maps', 'web agency', 'Ventimiglia', 45),
('google_maps', 'web agency', 'Sesto San Giovanni', 70),

-- GOOGLE MAPS - FABBRI
('google_maps', 'fabbri', 'Milano Centro', 80),
('google_maps', 'fabbri', 'Milano Navigli', 75),
('google_maps', 'fabbri', 'Roma Centro Storico', 80),
('google_maps', 'fabbri', 'Roma Eur', 75),
('google_maps', 'fabbri', 'Roma Trastevere', 70),
('google_maps', 'fabbri', 'Napoli Centro', 75),
('google_maps', 'fabbri', 'Napoli Vomero', 65),
('google_maps', 'fabbri', 'Torino Centro', 70),
('google_maps', 'fabbri', 'Bologna Centro', 70),
('google_maps', 'fabbri', 'Firenze Centro', 75),
('google_maps', 'fabbri', 'Palermo Centro', 65),
('google_maps', 'fabbri', 'Genova Centro', 65),
('google_maps', 'fabbri', 'Bari Centro', 60),
('google_maps', 'fabbri', 'Catania Centro', 60),
('google_maps', 'fabbri', 'Verona Centro', 65),
('google_maps', 'fabbri', 'Venezia Mestre', 60),
('google_maps', 'fabbri', 'Padova Centro', 60),
('google_maps', 'fabbri', 'Trieste Centro', 55),
('google_maps', 'fabbri', 'Brescia Centro', 60),
('google_maps', 'fabbri', 'Bergamo Bassa', 55),
('google_maps', 'fabbri', 'Lecce Centro', 55),
('google_maps', 'fabbri', 'Taranto Centro', 50),
('google_maps', 'fabbri', 'Reggio Calabria', 50),
('google_maps', 'fabbri', 'Perugia Centro', 55),
('google_maps', 'fabbri', 'Cagliari Centro', 55),
('google_maps', 'fabbri', 'Trento Centro', 55),
('google_maps', 'fabbri', 'Bolzano Centro', 55),
('google_maps', 'fabbri', 'Salerno Centro', 55),
('google_maps', 'fabbri', 'Rimini Centro', 55),
('google_maps', 'fabbri', 'Parma Centro', 55),
('google_maps', 'fabbri', 'Modena Centro', 55),
('google_maps', 'fabbri', 'Pescara Centro', 55),
('google_maps', 'fabbri', 'Livorno Centro', 50),
('google_maps', 'fabbri', 'Sassari Centro', 50),
('google_maps', 'fabbri', 'Ferrara Centro', 50),
('google_maps', 'fabbri', 'Latina Centro', 50),
('google_maps', 'fabbri', 'Arezzo Centro', 50),
('google_maps', 'fabbri', 'Pisa Centro', 50),
('google_maps', 'fabbri', 'Lucca Centro', 50),
('google_maps', 'fabbri', 'Foggia Centro', 45),
('google_maps', 'fabbri', 'L''Aquila Centro', 45),
('google_maps', 'fabbri', 'Grosseto Centro', 45),
('google_maps', 'fabbri', 'Treviso Centro', 50),
('google_maps', 'fabbri', 'Varese Centro', 50),
('google_maps', 'fabbri', 'Novara Centro', 45),
('google_maps', 'fabbri', 'Monza Centro', 55),
('google_maps', 'fabbri', 'Como Centro', 50),
('google_maps', 'fabbri', 'Vercelli', 45),
('google_maps', 'fabbri', 'Asti', 45),
('google_maps', 'fabbri', 'Alessandria', 45),
('google_maps', 'fabbri', 'Viterbo', 45),
('google_maps', 'fabbri', 'Terni', 45),
('google_maps', 'fabbri', 'Ragusa', 40),
('google_maps', 'fabbri', 'Siracusa', 45),
('google_maps', 'fabbri', 'Agrigento', 40),
('google_maps', 'fabbri', 'Trapani', 40),
('google_maps', 'fabbri', 'Cosenza', 45),
('google_maps', 'fabbri', 'Crotone', 40),
('google_maps', 'fabbri', 'Catanzaro', 45),
('google_maps', 'fabbri', 'Matera', 45),
('google_maps', 'fabbri', 'Potenza', 45),
('google_maps', 'fabbri', 'Campobasso', 40),
('google_maps', 'fabbri', 'Benevento', 40),
('google_maps', 'fabbri', 'Avellino', 40),
('google_maps', 'fabbri', 'Caserta', 45),
('google_maps', 'fabbri', 'Brindisi', 45),
('google_maps', 'fabbri', 'Andria', 40),
('google_maps', 'fabbri', 'Barletta', 40),
('google_maps', 'fabbri', 'Trani', 40),
('google_maps', 'fabbri', 'Molfetta', 40),
('google_maps', 'fabbri', 'Altamura', 40),
('google_maps', 'fabbri', 'Torre del Greco', 45),
('google_maps', 'fabbri', 'Giugliano in Campania', 45),
('google_maps', 'fabbri', 'Scafati', 40),
('google_maps', 'fabbri', 'Castellammare di Stabia', 45),
('google_maps', 'fabbri', 'Afragola', 40),
('google_maps', 'fabbri', 'Aversa', 40),
('google_maps', 'fabbri', 'Nocera Inferiore', 40),
('google_maps', 'fabbri', 'Cava de'' Tirreni', 40),
('google_maps', 'fabbri', 'Eboli', 40),
('google_maps', 'fabbri', 'Battipaglia', 40),
('google_maps', 'fabbri', 'Tivoli', 45),
('google_maps', 'fabbri', 'Guidonia Montecelio', 40),
('google_maps', 'fabbri', 'Pomezia', 45),
('google_maps', 'fabbri', 'Aprilia', 40),
('google_maps', 'fabbri', 'Frosinone', 45),
('google_maps', 'fabbri', 'Velletri', 40),
('google_maps', 'fabbri', 'Anzio', 45),
('google_maps', 'fabbri', 'Nettuno', 40),
('google_maps', 'fabbri', 'Ladispoli', 40),
('google_maps', 'fabbri', 'Civitavecchia', 45),
('google_maps', 'fabbri', 'Alghero', 45),
('google_maps', 'fabbri', 'Olbia', 50),
('google_maps', 'fabbri', 'Nuoro', 40),
('google_maps', 'fabbri', 'Iglesias', 40),
('google_maps', 'fabbri', 'Oristano', 40),
('google_maps', 'fabbri', 'Sanremo', 50),
('google_maps', 'fabbri', 'Imperia', 45),
('google_maps', 'fabbri', 'Ventimiglia', 40),
('google_maps', 'fabbri', 'Sesto San Giovanni', 55),

-- GOOGLE MAPS - FOTOGRAFI
('google_maps', 'fotografi', 'Milano Centro', 85),
('google_maps', 'fotografi', 'Milano Navigli', 80),
('google_maps', 'fotografi', 'Roma Centro Storico', 90),
('google_maps', 'fotografi', 'Roma Eur', 75),
('google_maps', 'fotografi', 'Roma Trastevere', 80),
('google_maps', 'fotografi', 'Napoli Centro', 80),
('google_maps', 'fotografi', 'Napoli Vomero', 70),
('google_maps', 'fotografi', 'Torino Centro', 75),
('google_maps', 'fotografi', 'Bologna Centro', 75),
('google_maps', 'fotografi', 'Firenze Centro', 85),
('google_maps', 'fotografi', 'Palermo Centro', 70),
('google_maps', 'fotografi', 'Genova Centro', 65),
('google_maps', 'fotografi', 'Bari Centro', 60),
('google_maps', 'fotografi', 'Catania Centro', 60),
('google_maps', 'fotografi', 'Verona Centro', 70),
('google_maps', 'fotografi', 'Venezia Mestre', 75),
('google_maps', 'fotografi', 'Padova Centro', 65),
('google_maps', 'fotografi', 'Trieste Centro', 60),
('google_maps', 'fotografi', 'Brescia Centro', 60),
('google_maps', 'fotografi', 'Bergamo Bassa', 60),
('google_maps', 'fotografi', 'Lecce Centro', 55),
('google_maps', 'fotografi', 'Taranto Centro', 50),
('google_maps', 'fotografi', 'Reggio Calabria', 50),
('google_maps', 'fotografi', 'Perugia Centro', 60),
('google_maps', 'fotografi', 'Cagliari Centro', 60),
('google_maps', 'fotografi', 'Trento Centro', 60),
('google_maps', 'fotografi', 'Bolzano Centro', 60),
('google_maps', 'fotografi', 'Salerno Centro', 55),
('google_maps', 'fotografi', 'Rimini Centro', 65),
('google_maps', 'fotografi', 'Parma Centro', 60),
('google_maps', 'fotografi', 'Modena Centro', 60),
('google_maps', 'fotografi', 'Pescara Centro', 55),
('google_maps', 'fotografi', 'Livorno Centro', 55),
('google_maps', 'fotografi', 'Sassari Centro', 50),
('google_maps', 'fotografi', 'Ferrara Centro', 55),
('google_maps', 'fotografi', 'Latina Centro', 50),
('google_maps', 'fotografi', 'Arezzo Centro', 55),
('google_maps', 'fotografi', 'Pisa Centro', 60),
('google_maps', 'fotografi', 'Lucca Centro', 60),
('google_maps', 'fotografi', 'Foggia Centro', 45),
('google_maps', 'fotografi', 'L''Aquila Centro', 45),
('google_maps', 'fotografi', 'Grosseto Centro', 45),
('google_maps', 'fotografi', 'Treviso Centro', 55),
('google_maps', 'fotografi', 'Varese Centro', 55),
('google_maps', 'fotografi', 'Novara Centro', 50),
('google_maps', 'fotografi', 'Monza Centro', 60),
('google_maps', 'fotografi', 'Como Centro', 60),
('google_maps', 'fotografi', 'Vercelli', 45),
('google_maps', 'fotografi', 'Asti', 45),
('google_maps', 'fotografi', 'Alessandria', 45),
('google_maps', 'fotografi', 'Viterbo', 45),
('google_maps', 'fotografi', 'Terni', 45),
('google_maps', 'fotografi', 'Ragusa', 45),
('google_maps', 'fotografi', 'Siracusa', 50),
('google_maps', 'fotografi', 'Agrigento', 45),
('google_maps', 'fotografi', 'Trapani', 45),
('google_maps', 'fotografi', 'Cosenza', 45),
('google_maps', 'fotografi', 'Crotone', 40),
('google_maps', 'fotografi', 'Catanzaro', 45),
('google_maps', 'fotografi', 'Matera', 55),
('google_maps', 'fotografi', 'Potenza', 45),
('google_maps', 'fotografi', 'Campobasso', 40),
('google_maps', 'fotografi', 'Benevento', 40),
('google_maps', 'fotografi', 'Avellino', 40),
('google_maps', 'fotografi', 'Caserta', 45),
('google_maps', 'fotografi', 'Brindisi', 45),
('google_maps', 'fotografi', 'Andria', 40),
('google_maps', 'fotografi', 'Barletta', 40),
('google_maps', 'fotografi', 'Trani', 40),
('google_maps', 'fotografi', 'Molfetta', 40),
('google_maps', 'fotografi', 'Altamura', 40),
('google_maps', 'fotografi', 'Torre del Greco', 45),
('google_maps', 'fotografi', 'Giugliano in Campania', 45),
('google_maps', 'fotografi', 'Scafati', 40),
('google_maps', 'fotografi', 'Castellammare di Stabia', 45),
('google_maps', 'fotografi', 'Afragola', 40),
('google_maps', 'fotografi', 'Aversa', 40),
('google_maps', 'fotografi', 'Nocera Inferiore', 40),
('google_maps', 'fotografi', 'Cava de'' Tirreni', 40),
('google_maps', 'fotografi', 'Eboli', 40),
('google_maps', 'fotografi', 'Battipaglia', 40),
('google_maps', 'fotografi', 'Tivoli', 50),
('google_maps', 'fotografi', 'Guidonia Montecelio', 40),
('google_maps', 'fotografi', 'Pomezia', 45),
('google_maps', 'fotografi', 'Aprilia', 40),
('google_maps', 'fotografi', 'Frosinone', 45),
('google_maps', 'fotografi', 'Velletri', 40),
('google_maps', 'fotografi', 'Anzio', 50),
('google_maps', 'fotografi', 'Nettuno', 45),
('google_maps', 'fotografi', 'Ladispoli', 40),
('google_maps', 'fotografi', 'Civitavecchia', 45),
('google_maps', 'fotografi', 'Alghero', 55),
('google_maps', 'fotografi', 'Olbia', 60),
('google_maps', 'fotografi', 'Nuoro', 40),
('google_maps', 'fotografi', 'Iglesias', 40),
('google_maps', 'fotografi', 'Oristano', 40),
('google_maps', 'fotografi', 'Sanremo', 65),
('google_maps', 'fotografi', 'Imperia', 50),
('google_maps', 'fotografi', 'Ventimiglia', 45),
('google_maps', 'fotografi', 'Sesto San Giovanni', 60)

ON CONFLICT (source, category, location_name) DO NOTHING;

-- Ora ripetiamo tutto per YELP (500 righe)
INSERT INTO zones_to_scrape (source, category, location_name, score) 
SELECT 'yelp' as source, category, location_name, GREATEST(score - 10, 30) as score 
FROM zones_to_scrape 
WHERE source = 'google_maps'
ON CONFLICT (source, category, location_name) DO NOTHING;

-- Ora ripetiamo tutto per PAGINE GIALLE (500 righe)  
INSERT INTO zones_to_scrape (source, category, location_name, score) 
SELECT 'pagine_gialle' as source, category, location_name, GREATEST(score - 20, 25) as score 
FROM zones_to_scrape 
WHERE source = 'google_maps'
ON CONFLICT (source, category, location_name) DO NOTHING;

-- Mostra statistiche finali
SELECT 
  source,
  category,
  COUNT(*) as zone_count,
  AVG(score) as avg_score,
  MIN(score) as min_score,
  MAX(score) as max_score
FROM zones_to_scrape 
GROUP BY source, category 
ORDER BY source, category;

-- Mostra totale generale
SELECT 
  COUNT(*) as total_zones,
  COUNT(DISTINCT location_name) as unique_locations,
  COUNT(DISTINCT source) as sources,
  COUNT(DISTINCT category) as categories
FROM zones_to_scrape;
